sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    otherSprite.destroy()
    info.changeScoreBy(1)
})
let projectile: Sprite = null
let shark = sprites.create(assets.image`shark`, SpriteKind.Player)
let snail = sprites.create(assets.image`snail`, SpriteKind.Food)
shark.setPosition(12, 47)
snail.setPosition(136, 43)
snail.setVelocity(15, 15)
snail.setBounceOnWall(true)
controller.moveSprite(shark)
game.splash("food run")
shark.setStayInScreen(true)
let duck = sprites.create(assets.image`duck`, SpriteKind.Food)
duck.setPosition(12, 12)
duck.setPosition(64, 105)
duck.setVelocity(15, 15)
duck.setBounceOnWall(true)
let bone = sprites.create(assets.image`bone`, SpriteKind.Food)
bone.setPosition(136, 61)
duck.setPosition(146, 16)
bone.setVelocity(15, 15)
bone.setBounceOnWall(true)
let direction = 1
info.setLife(3)
game.onUpdateInterval(200, function () {
    projectile = sprites.createProjectileFromSide(assets.image`ball`, direction * 50, 0)
    projectile.y = randint(5, 115)
    direction = direction * -1
})
